CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_presets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    category VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    base_price INT UNSIGNED NOT NULL DEFAULT 0,
    default_hours DECIMAL(6,2) NOT NULL DEFAULT 1.00,
    risk_level VARCHAR(40) NOT NULL DEFAULT 'rendah',
    note TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS addon_services (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    price INT UNSIGNED NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estimates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    estimate_code VARCHAR(40) NOT NULL UNIQUE,
    client_name VARCHAR(120) NOT NULL,
    client_phone VARCHAR(80) NULL,
    client_type VARCHAR(80) NULL,
    location VARCHAR(160) NULL,
    client_notes TEXT NULL,
    device_type VARCHAR(100) NOT NULL,
    device_brand VARCHAR(120) NULL,
    device_model VARCHAR(120) NULL,
    device_age VARCHAR(80) NULL,
    physical_condition VARCHAR(120) NULL,
    official_warranty VARCHAR(80) NULL,
    service_preset_id INT UNSIGNED NULL,
    service_name VARCHAR(180) NOT NULL,
    addon_json JSON NULL,
    difficulty VARCHAR(40) NULL,
    risk_level VARCHAR(40) NULL,
    urgency VARCHAR(40) NULL,
    warranty VARCHAR(40) NULL,
    sparepart_cost INT UNSIGNED NOT NULL DEFAULT 0,
    shipping_cost INT UNSIGNED NOT NULL DEFAULT 0,
    material_cost INT UNSIGNED NOT NULL DEFAULT 0,
    transport_cost INT UNSIGNED NOT NULL DEFAULT 0,
    parking_cost INT UNSIGNED NOT NULL DEFAULT 0,
    third_party_cost INT UNSIGNED NOT NULL DEFAULT 0,
    hourly_rate INT UNSIGNED NOT NULL DEFAULT 0,
    work_hours DECIMAL(6,2) NOT NULL DEFAULT 0,
    testing_minutes INT UNSIGNED NOT NULL DEFAULT 0,
    communication_minutes INT UNSIGNED NOT NULL DEFAULT 0,
    margin_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
    minimum_margin_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
    discount INT UNSIGNED NOT NULL DEFAULT 0,
    rounding_base INT UNSIGNED NOT NULL DEFAULT 5000,
    modal_total INT UNSIGNED NOT NULL DEFAULT 0,
    jasa_dasar INT UNSIGNED NOT NULL DEFAULT 0,
    time_cost INT UNSIGNED NOT NULL DEFAULT 0,
    risk_fee INT UNSIGNED NOT NULL DEFAULT 0,
    jasa_total INT UNSIGNED NOT NULL DEFAULT 0,
    subtotal INT UNSIGNED NOT NULL DEFAULT 0,
    urgency_fee INT UNSIGNED NOT NULL DEFAULT 0,
    warranty_fee INT UNSIGNED NOT NULL DEFAULT 0,
    before_margin INT UNSIGNED NOT NULL DEFAULT 0,
    margin_profit INT UNSIGNED NOT NULL DEFAULT 0,
    minimal_price INT UNSIGNED NOT NULL DEFAULT 0,
    ideal_price INT UNSIGNED NOT NULL DEFAULT 0,
    range_low INT UNSIGNED NOT NULL DEFAULT 0,
    range_high INT UNSIGNED NOT NULL DEFAULT 0,
    nego_price INT UNSIGNED NOT NULL DEFAULT 0,
    profit INT UNSIGNED NOT NULL DEFAULT 0,
    profit_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
    dp INT UNSIGNED NOT NULL DEFAULT 0,
    whatsapp_message TEXT NULL,
    warnings_json JSON NULL,
    status ENUM('draft','sent','deal','rejected','revised','paid','done') NOT NULL DEFAULT 'draft',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_created_at (created_at),
    INDEX idx_status (status),
    INDEX idx_client_name (client_name),
    CONSTRAINT fk_estimates_preset FOREIGN KEY (service_preset_id) REFERENCES service_presets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
